// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lsc-dag/CrystalLattice.tsx": () => import("../components/mockups/lsc-dag/CrystalLattice.tsx"),
  "./components/mockups/lsc-dag/DnaHelix.tsx": () => import("../components/mockups/lsc-dag/DnaHelix.tsx"),
  "./components/mockups/lsc-dag/GalaxySpiral.tsx": () => import("../components/mockups/lsc-dag/GalaxySpiral.tsx"),
  "./components/mockups/soulware-brain/HolographicBrain.tsx": () => import("../components/mockups/soulware-brain/HolographicBrain.tsx"),
  "./components/mockups/soulware-brain/NeuralMesh.tsx": () => import("../components/mockups/soulware-brain/NeuralMesh.tsx"),
  "./components/mockups/soulware-brain/QuantumCore.tsx": () => import("../components/mockups/soulware-brain/QuantumCore.tsx")
};
